# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('pinecone')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def api_key(self) -> Optional[str]:
        """
        Pinecone API Key. Can be configured by setting PINECONE_API_KEY environment variable.
        """
        return __config__.get('apiKey') or _utilities.get_env('PINECONE_API_KEY')

    @_builtins.property
    def client_id(self) -> Optional[str]:
        """
        Pinecone Client ID for admin operations. Can be configured by setting PINECONE_CLIENT_ID environment variable.
        """
        return __config__.get('clientId') or _utilities.get_env('PINECONE_CLIENT_ID')

    @_builtins.property
    def client_secret(self) -> Optional[str]:
        """
        Pinecone Client Secret for admin operations. Can be configured by setting PINECONE_CLIENT_SECRET environment variable.
        """
        return __config__.get('clientSecret') or _utilities.get_env('PINECONE_CLIENT_SECRET')

