# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .api_key import *
from .collection import *
from .get import *
from .get_collection import *
from .get_collections import *
from .get_es import *
from .index import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pinecone_pulumi.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pinecone_pulumi.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pinecone",
  "mod": "index/apiKey",
  "fqn": "pinecone_pulumi",
  "classes": {
   "pinecone:index/apiKey:ApiKey": "ApiKey"
  }
 },
 {
  "pkg": "pinecone",
  "mod": "index/collection",
  "fqn": "pinecone_pulumi",
  "classes": {
   "pinecone:index/collection:Collection": "Collection"
  }
 },
 {
  "pkg": "pinecone",
  "mod": "index/index",
  "fqn": "pinecone_pulumi",
  "classes": {
   "pinecone:index/index:Index": "Index"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pinecone",
  "token": "pulumi:providers:pinecone",
  "fqn": "pinecone_pulumi",
  "class": "Provider"
 }
]
"""
)
