# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'IndexMetric',
    'ServerlessSpecCloud',
]


class IndexMetric(str, Enum):
    DOTPRODUCT = "dotproduct"
    COSINE = "cosine"
    EUCLIDEAN = "euclidean"


class ServerlessSpecCloud(str, Enum):
    AWS = "aws"
    AZURE = "azure"
    GCP = "gcp"
