# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['CollectionArgs', 'Collection']

@pulumi.input_type
class CollectionArgs:
    def __init__(__self__, *,
                 source: pulumi.Input[_builtins.str],
                 dimension: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 size: Optional[pulumi.Input[_builtins.int]] = None,
                 timeouts: Optional[pulumi.Input['CollectionTimeoutsArgs']] = None,
                 vector_count: Optional[pulumi.Input[_builtins.int]] = None):
        """
        The set of arguments for constructing a Collection resource.
        :param pulumi.Input[_builtins.str] source: The name of the source index to be used as the source for the collection.
        :param pulumi.Input[_builtins.int] dimension: The dimension of the vectors stored in each record held in the collection.
        :param pulumi.Input[_builtins.str] name: The name of the collection.
        :param pulumi.Input[_builtins.int] size: The size of the collection in bytes.
        :param pulumi.Input[_builtins.int] vector_count: The number of records stored in the collection.
        """
        pulumi.set(__self__, "source", source)
        if dimension is not None:
            pulumi.set(__self__, "dimension", dimension)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if size is not None:
            pulumi.set(__self__, "size", size)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)
        if vector_count is not None:
            pulumi.set(__self__, "vector_count", vector_count)

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the source index to be used as the source for the collection.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter
    def dimension(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The dimension of the vectors stored in each record held in the collection.
        """
        return pulumi.get(self, "dimension")

    @dimension.setter
    def dimension(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "dimension", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the collection.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def size(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The size of the collection in bytes.
        """
        return pulumi.get(self, "size")

    @size.setter
    def size(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "size", value)

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['CollectionTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['CollectionTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)

    @_builtins.property
    @pulumi.getter(name="vectorCount")
    def vector_count(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The number of records stored in the collection.
        """
        return pulumi.get(self, "vector_count")

    @vector_count.setter
    def vector_count(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "vector_count", value)


@pulumi.input_type
class _CollectionState:
    def __init__(__self__, *,
                 dimension: Optional[pulumi.Input[_builtins.int]] = None,
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 size: Optional[pulumi.Input[_builtins.int]] = None,
                 source: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 timeouts: Optional[pulumi.Input['CollectionTimeoutsArgs']] = None,
                 vector_count: Optional[pulumi.Input[_builtins.int]] = None):
        """
        Input properties used for looking up and filtering Collection resources.
        :param pulumi.Input[_builtins.int] dimension: The dimension of the vectors stored in each record held in the collection.
        :param pulumi.Input[_builtins.str] environment: The environment where the collection is hosted.
        :param pulumi.Input[_builtins.str] name: The name of the collection.
        :param pulumi.Input[_builtins.int] size: The size of the collection in bytes.
        :param pulumi.Input[_builtins.str] source: The name of the source index to be used as the source for the collection.
        :param pulumi.Input[_builtins.str] status: The status of the collection.
        :param pulumi.Input[_builtins.int] vector_count: The number of records stored in the collection.
        """
        if dimension is not None:
            pulumi.set(__self__, "dimension", dimension)
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if size is not None:
            pulumi.set(__self__, "size", size)
        if source is not None:
            pulumi.set(__self__, "source", source)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)
        if vector_count is not None:
            pulumi.set(__self__, "vector_count", vector_count)

    @_builtins.property
    @pulumi.getter
    def dimension(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The dimension of the vectors stored in each record held in the collection.
        """
        return pulumi.get(self, "dimension")

    @dimension.setter
    def dimension(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "dimension", value)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The environment where the collection is hosted.
        """
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the collection.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def size(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The size of the collection in bytes.
        """
        return pulumi.get(self, "size")

    @size.setter
    def size(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "size", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the source index to be used as the source for the collection.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The status of the collection.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['CollectionTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['CollectionTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)

    @_builtins.property
    @pulumi.getter(name="vectorCount")
    def vector_count(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The number of records stored in the collection.
        """
        return pulumi.get(self, "vector_count")

    @vector_count.setter
    def vector_count(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "vector_count", value)


@pulumi.type_token("pinecone:index/collection:Collection")
class Collection(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 dimension: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 size: Optional[pulumi.Input[_builtins.int]] = None,
                 source: Optional[pulumi.Input[_builtins.str]] = None,
                 timeouts: Optional[pulumi.Input[Union['CollectionTimeoutsArgs', 'CollectionTimeoutsArgsDict']]] = None,
                 vector_count: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        """
        The `Collection` resource lets you create and manage collections in Pinecone. Learn more about collections in the docs.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_pinecone as pinecone

        test = pinecone.Index("test",
            name="tftestindex",
            dimension=10,
            spec={
                "pod": {
                    "environment": "us-west4-gcp",
                    "pod_type": "s1.x1",
                },
            })
        test_collection = pinecone.Collection("test",
            name="tftestcollection",
            source=test.name)
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] dimension: The dimension of the vectors stored in each record held in the collection.
        :param pulumi.Input[_builtins.str] name: The name of the collection.
        :param pulumi.Input[_builtins.int] size: The size of the collection in bytes.
        :param pulumi.Input[_builtins.str] source: The name of the source index to be used as the source for the collection.
        :param pulumi.Input[_builtins.int] vector_count: The number of records stored in the collection.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CollectionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The `Collection` resource lets you create and manage collections in Pinecone. Learn more about collections in the docs.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_pinecone as pinecone

        test = pinecone.Index("test",
            name="tftestindex",
            dimension=10,
            spec={
                "pod": {
                    "environment": "us-west4-gcp",
                    "pod_type": "s1.x1",
                },
            })
        test_collection = pinecone.Collection("test",
            name="tftestcollection",
            source=test.name)
        ```

        :param str resource_name: The name of the resource.
        :param CollectionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CollectionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 dimension: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 size: Optional[pulumi.Input[_builtins.int]] = None,
                 source: Optional[pulumi.Input[_builtins.str]] = None,
                 timeouts: Optional[pulumi.Input[Union['CollectionTimeoutsArgs', 'CollectionTimeoutsArgsDict']]] = None,
                 vector_count: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CollectionArgs.__new__(CollectionArgs)

            __props__.__dict__["dimension"] = dimension
            __props__.__dict__["name"] = name
            __props__.__dict__["size"] = size
            if source is None and not opts.urn:
                raise TypeError("Missing required property 'source'")
            __props__.__dict__["source"] = source
            __props__.__dict__["timeouts"] = timeouts
            __props__.__dict__["vector_count"] = vector_count
            __props__.__dict__["environment"] = None
            __props__.__dict__["status"] = None
        super(Collection, __self__).__init__(
            'pinecone:index/collection:Collection',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            dimension: Optional[pulumi.Input[_builtins.int]] = None,
            environment: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            size: Optional[pulumi.Input[_builtins.int]] = None,
            source: Optional[pulumi.Input[_builtins.str]] = None,
            status: Optional[pulumi.Input[_builtins.str]] = None,
            timeouts: Optional[pulumi.Input[Union['CollectionTimeoutsArgs', 'CollectionTimeoutsArgsDict']]] = None,
            vector_count: Optional[pulumi.Input[_builtins.int]] = None) -> 'Collection':
        """
        Get an existing Collection resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] dimension: The dimension of the vectors stored in each record held in the collection.
        :param pulumi.Input[_builtins.str] environment: The environment where the collection is hosted.
        :param pulumi.Input[_builtins.str] name: The name of the collection.
        :param pulumi.Input[_builtins.int] size: The size of the collection in bytes.
        :param pulumi.Input[_builtins.str] source: The name of the source index to be used as the source for the collection.
        :param pulumi.Input[_builtins.str] status: The status of the collection.
        :param pulumi.Input[_builtins.int] vector_count: The number of records stored in the collection.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CollectionState.__new__(_CollectionState)

        __props__.__dict__["dimension"] = dimension
        __props__.__dict__["environment"] = environment
        __props__.__dict__["name"] = name
        __props__.__dict__["size"] = size
        __props__.__dict__["source"] = source
        __props__.__dict__["status"] = status
        __props__.__dict__["timeouts"] = timeouts
        __props__.__dict__["vector_count"] = vector_count
        return Collection(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def dimension(self) -> pulumi.Output[_builtins.int]:
        """
        The dimension of the vectors stored in each record held in the collection.
        """
        return pulumi.get(self, "dimension")

    @_builtins.property
    @pulumi.getter
    def environment(self) -> pulumi.Output[_builtins.str]:
        """
        The environment where the collection is hosted.
        """
        return pulumi.get(self, "environment")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the collection.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def size(self) -> pulumi.Output[_builtins.int]:
        """
        The size of the collection in bytes.
        """
        return pulumi.get(self, "size")

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the source index to be used as the source for the collection.
        """
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        The status of the collection.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> pulumi.Output[Optional['outputs.CollectionTimeouts']]:
        return pulumi.get(self, "timeouts")

    @_builtins.property
    @pulumi.getter(name="vectorCount")
    def vector_count(self) -> pulumi.Output[_builtins.int]:
        """
        The number of records stored in the collection.
        """
        return pulumi.get(self, "vector_count")

