# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetEsResult',
    'AwaitableGetEsResult',
    'get_es',
    'get_es_output',
]

@pulumi.output_type
class GetEsResult:
    """
    A collection of values returned by getEs.
    """
    def __init__(__self__, id=None, indexes=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if indexes and not isinstance(indexes, list):
            raise TypeError("Expected argument 'indexes' to be a list")
        pulumi.set(__self__, "indexes", indexes)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Indexes identifier
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def indexes(self) -> Sequence['outputs.GetEsIndexResult']:
        """
        List of the indexes in your project
        """
        return pulumi.get(self, "indexes")


class AwaitableGetEsResult(GetEsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetEsResult(
            id=self.id,
            indexes=self.indexes)


def get_es(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetEsResult:
    """
    Indexes data source
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('pinecone:index/getEs:getEs', __args__, opts=opts, typ=GetEsResult).value

    return AwaitableGetEsResult(
        id=pulumi.get(__ret__, 'id'),
        indexes=pulumi.get(__ret__, 'indexes'))
def get_es_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetEsResult]:
    """
    Indexes data source
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('pinecone:index/getEs:getEs', __args__, opts=opts, typ=GetEsResult)
    return __ret__.apply(lambda __response__: GetEsResult(
        id=pulumi.get(__response__, 'id'),
        indexes=pulumi.get(__response__, 'indexes')))
