# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetCollectionsResult',
    'AwaitableGetCollectionsResult',
    'get_collections',
    'get_collections_output',
]

@pulumi.output_type
class GetCollectionsResult:
    """
    A collection of values returned by getCollections.
    """
    def __init__(__self__, collections=None, id=None):
        if collections and not isinstance(collections, list):
            raise TypeError("Expected argument 'collections' to be a list")
        pulumi.set(__self__, "collections", collections)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter
    def collections(self) -> Sequence['outputs.GetCollectionsCollectionResult']:
        """
        List of the collections in your project
        """
        return pulumi.get(self, "collections")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Collections identifier
        """
        return pulumi.get(self, "id")


class AwaitableGetCollectionsResult(GetCollectionsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCollectionsResult(
            collections=self.collections,
            id=self.id)


def get_collections(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCollectionsResult:
    """
    Collections data source
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('pinecone:index/getCollections:getCollections', __args__, opts=opts, typ=GetCollectionsResult).value

    return AwaitableGetCollectionsResult(
        collections=pulumi.get(__ret__, 'collections'),
        id=pulumi.get(__ret__, 'id'))
def get_collections_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCollectionsResult]:
    """
    Collections data source
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('pinecone:index/getCollections:getCollections', __args__, opts=opts, typ=GetCollectionsResult)
    return __ret__.apply(lambda __response__: GetCollectionsResult(
        collections=pulumi.get(__response__, 'collections'),
        id=pulumi.get(__response__, 'id')))
