archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'

before:
  hooks:
    - make provider
builds:
  - binary: pulumi-resource-pinecone
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/pinecone-io/pulumi-pinecone/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-pinecone/

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '-y'
      - '--output-certificate=${certificate}'
      - '--bundle=${signature}'
      - '${artifact}'
    artifacts: all
    output: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

source:
  enabled: true

release:
  disable: false
  prerelease: auto

snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
