// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone
{
    /// <summary>
    /// The `pinecone.Collection` resource lets you create and manage collections in Pinecone. Learn more about collections in the docs.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Pinecone = Pulumi.Pinecone;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var test = new Pinecone.Index("test", new()
    ///     {
    ///         Name = "tftestindex",
    ///         Dimension = 10,
    ///         Spec = new Pinecone.Inputs.IndexSpecArgs
    ///         {
    ///             Pod = new Pinecone.Inputs.IndexSpecPodArgs
    ///             {
    ///                 Environment = "us-west4-gcp",
    ///                 PodType = "s1.x1",
    ///             },
    ///         },
    ///     });
    /// 
    ///     var testCollection = new Pinecone.Collection("test", new()
    ///     {
    ///         Name = "tftestcollection",
    ///         Source = test.Name,
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [PineconeResourceType("pinecone:index/collection:Collection")]
    public partial class Collection : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The dimension of the vectors stored in each record held in the collection.
        /// </summary>
        [Output("dimension")]
        public Output<int> Dimension { get; private set; } = null!;

        /// <summary>
        /// The environment where the collection is hosted.
        /// </summary>
        [Output("environment")]
        public Output<string> Environment { get; private set; } = null!;

        /// <summary>
        /// The name of the collection.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The size of the collection in bytes.
        /// </summary>
        [Output("size")]
        public Output<int> Size { get; private set; } = null!;

        /// <summary>
        /// The name of the source index to be used as the source for the collection.
        /// </summary>
        [Output("source")]
        public Output<string> Source { get; private set; } = null!;

        /// <summary>
        /// The status of the collection.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.CollectionTimeouts?> Timeouts { get; private set; } = null!;

        /// <summary>
        /// The number of records stored in the collection.
        /// </summary>
        [Output("vectorCount")]
        public Output<int> VectorCount { get; private set; } = null!;


        /// <summary>
        /// Create a Collection resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Collection(string name, CollectionArgs args, CustomResourceOptions? options = null)
            : base("pinecone:index/collection:Collection", name, args ?? new CollectionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Collection(string name, Input<string> id, CollectionState? state = null, CustomResourceOptions? options = null)
            : base("pinecone:index/collection:Collection", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pinecone-io/pulumi-pinecone",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Collection resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Collection Get(string name, Input<string> id, CollectionState? state = null, CustomResourceOptions? options = null)
        {
            return new Collection(name, id, state, options);
        }
    }

    public sealed class CollectionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The dimension of the vectors stored in each record held in the collection.
        /// </summary>
        [Input("dimension")]
        public Input<int>? Dimension { get; set; }

        /// <summary>
        /// The name of the collection.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The size of the collection in bytes.
        /// </summary>
        [Input("size")]
        public Input<int>? Size { get; set; }

        /// <summary>
        /// The name of the source index to be used as the source for the collection.
        /// </summary>
        [Input("source", required: true)]
        public Input<string> Source { get; set; } = null!;

        [Input("timeouts")]
        public Input<Inputs.CollectionTimeoutsArgs>? Timeouts { get; set; }

        /// <summary>
        /// The number of records stored in the collection.
        /// </summary>
        [Input("vectorCount")]
        public Input<int>? VectorCount { get; set; }

        public CollectionArgs()
        {
        }
        public static new CollectionArgs Empty => new CollectionArgs();
    }

    public sealed class CollectionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The dimension of the vectors stored in each record held in the collection.
        /// </summary>
        [Input("dimension")]
        public Input<int>? Dimension { get; set; }

        /// <summary>
        /// The environment where the collection is hosted.
        /// </summary>
        [Input("environment")]
        public Input<string>? Environment { get; set; }

        /// <summary>
        /// The name of the collection.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The size of the collection in bytes.
        /// </summary>
        [Input("size")]
        public Input<int>? Size { get; set; }

        /// <summary>
        /// The name of the source index to be used as the source for the collection.
        /// </summary>
        [Input("source")]
        public Input<string>? Source { get; set; }

        /// <summary>
        /// The status of the collection.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("timeouts")]
        public Input<Inputs.CollectionTimeoutsGetArgs>? Timeouts { get; set; }

        /// <summary>
        /// The number of records stored in the collection.
        /// </summary>
        [Input("vectorCount")]
        public Input<int>? VectorCount { get; set; }

        public CollectionState()
        {
        }
        public static new CollectionState Empty => new CollectionState();
    }
}
