// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone
{
    public static class GetCollection
    {
        /// <summary>
        /// Collection data source
        /// </summary>
        public static Task<GetCollectionResult> InvokeAsync(GetCollectionArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCollectionResult>("pinecone:index/getCollection:getCollection", args ?? new GetCollectionArgs(), options.WithDefaults());

        /// <summary>
        /// Collection data source
        /// </summary>
        public static Output<GetCollectionResult> Invoke(GetCollectionInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCollectionResult>("pinecone:index/getCollection:getCollection", args ?? new GetCollectionInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Collection data source
        /// </summary>
        public static Output<GetCollectionResult> Invoke(GetCollectionInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCollectionResult>("pinecone:index/getCollection:getCollection", args ?? new GetCollectionInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCollectionArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the collection.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetCollectionArgs()
        {
        }
        public static new GetCollectionArgs Empty => new GetCollectionArgs();
    }

    public sealed class GetCollectionInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the collection.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetCollectionInvokeArgs()
        {
        }
        public static new GetCollectionInvokeArgs Empty => new GetCollectionInvokeArgs();
    }


    [OutputType]
    public sealed class GetCollectionResult
    {
        /// <summary>
        /// The dimension of the vectors stored in each record held in the collection.
        /// </summary>
        public readonly int Dimension;
        /// <summary>
        /// The environment where the collection is hosted.
        /// </summary>
        public readonly string Environment;
        /// <summary>
        /// Collection identifier
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the collection.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The size of the collection in bytes.
        /// </summary>
        public readonly int Size;
        /// <summary>
        /// The status of the collection.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// The number of records stored in the collection.
        /// </summary>
        public readonly int VectorCount;

        [OutputConstructor]
        private GetCollectionResult(
            int dimension,

            string environment,

            string id,

            string name,

            int size,

            string status,

            int vectorCount)
        {
            Dimension = dimension;
            Environment = environment;
            Id = id;
            Name = name;
            Size = size;
            Status = status;
            VectorCount = vectorCount;
        }
    }
}
