// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone
{
    public static class GetCollections
    {
        /// <summary>
        /// Collections data source
        /// </summary>
        public static Task<GetCollectionsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCollectionsResult>("pinecone:index/getCollections:getCollections", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Collections data source
        /// </summary>
        public static Output<GetCollectionsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCollectionsResult>("pinecone:index/getCollections:getCollections", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Collections data source
        /// </summary>
        public static Output<GetCollectionsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCollectionsResult>("pinecone:index/getCollections:getCollections", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetCollectionsResult
    {
        /// <summary>
        /// List of the collections in your project
        /// </summary>
        public readonly ImmutableArray<Outputs.GetCollectionsCollectionResult> Collections;
        /// <summary>
        /// Collections identifier
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetCollectionsResult(
            ImmutableArray<Outputs.GetCollectionsCollectionResult> collections,

            string id)
        {
            Collections = collections;
            Id = id;
        }
    }
}
