// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone
{
    /// <summary>
    /// The `pinecone.Index` resource lets you create and manage indexes in Pinecone. Learn more about indexes in the [docs](https://docs.pinecone.io/guides/indexes/understanding-indexes).
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Pinecone = Pulumi.Pinecone;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var test = new Pinecone.Index("test", new()
    ///     {
    ///         Name = "tftestindex",
    ///         Dimension = 10,
    ///         Spec = new Pinecone.Inputs.IndexSpecArgs
    ///         {
    ///             Serverless = new Pinecone.Inputs.IndexSpecServerlessArgs
    ///             {
    ///                 Cloud = "aws",
    ///                 Region = "us-west-2",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [PineconeResourceType("pinecone:index/index:Index")]
    public partial class Index : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether deletion protection for the index is enabled. You can use 'enabled', or 'disabled'.
        /// </summary>
        [Output("deletionProtection")]
        public Output<string> DeletionProtection { get; private set; } = null!;

        /// <summary>
        /// The dimensions of the vectors to be inserted in the index
        /// </summary>
        [Output("dimension")]
        public Output<int> Dimension { get; private set; } = null!;

        /// <summary>
        /// Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
        /// </summary>
        [Output("embed")]
        public Output<Outputs.IndexEmbed> Embed { get; private set; } = null!;

        /// <summary>
        /// The URL address where the index is hosted.
        /// </summary>
        [Output("host")]
        public Output<string> Host { get; private set; } = null!;

        /// <summary>
        /// The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If the 'vector_type' is 'sparse', the metric must be 'dotproduct'. If the VectorType is dense, the metric defaults to 'cosine'.
        /// </summary>
        [Output("metric")]
        public Output<string> Metric { get; private set; } = null!;

        /// <summary>
        /// The name of the index to be created. The maximum length is 45 characters.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Spec
        /// </summary>
        [Output("spec")]
        public Output<Outputs.IndexSpec?> Spec { get; private set; } = null!;

        /// <summary>
        /// Status
        /// </summary>
        [Output("status")]
        public Output<Outputs.IndexStatus> Status { get; private set; } = null!;

        /// <summary>
        /// Custom user tags added to an index. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '', or '-'. Values must be alphanumeric, ';', '@', '', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableDictionary<string, string>> Tags { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.IndexTimeouts?> Timeouts { get; private set; } = null!;

        /// <summary>
        /// The index vector type. You can use 'dense' or 'sparse'. If 'dense', the vector dimension must be specified. If 'sparse', the vector dimension should not be specified.
        /// </summary>
        [Output("vectorType")]
        public Output<string> VectorType { get; private set; } = null!;


        /// <summary>
        /// Create a Index resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Index(string name, IndexArgs? args = null, CustomResourceOptions? options = null)
            : base("pinecone:index/index:Index", name, args ?? new IndexArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Index(string name, Input<string> id, IndexState? state = null, CustomResourceOptions? options = null)
            : base("pinecone:index/index:Index", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pinecone-io/pulumi-pinecone",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Index resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Index Get(string name, Input<string> id, IndexState? state = null, CustomResourceOptions? options = null)
        {
            return new Index(name, id, state, options);
        }
    }

    public sealed class IndexArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether deletion protection for the index is enabled. You can use 'enabled', or 'disabled'.
        /// </summary>
        [Input("deletionProtection")]
        public Input<string>? DeletionProtection { get; set; }

        /// <summary>
        /// The dimensions of the vectors to be inserted in the index
        /// </summary>
        [Input("dimension")]
        public Input<int>? Dimension { get; set; }

        /// <summary>
        /// Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
        /// </summary>
        [Input("embed")]
        public Input<Inputs.IndexEmbedArgs>? Embed { get; set; }

        /// <summary>
        /// The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If the 'vector_type' is 'sparse', the metric must be 'dotproduct'. If the VectorType is dense, the metric defaults to 'cosine'.
        /// </summary>
        [Input("metric")]
        public Input<string>? Metric { get; set; }

        /// <summary>
        /// The name of the index to be created. The maximum length is 45 characters.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Spec
        /// </summary>
        [Input("spec")]
        public Input<Inputs.IndexSpecArgs>? Spec { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Custom user tags added to an index. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '', or '-'. Values must be alphanumeric, ';', '@', '', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        [Input("timeouts")]
        public Input<Inputs.IndexTimeoutsArgs>? Timeouts { get; set; }

        /// <summary>
        /// The index vector type. You can use 'dense' or 'sparse'. If 'dense', the vector dimension must be specified. If 'sparse', the vector dimension should not be specified.
        /// </summary>
        [Input("vectorType")]
        public Input<string>? VectorType { get; set; }

        public IndexArgs()
        {
        }
        public static new IndexArgs Empty => new IndexArgs();
    }

    public sealed class IndexState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether deletion protection for the index is enabled. You can use 'enabled', or 'disabled'.
        /// </summary>
        [Input("deletionProtection")]
        public Input<string>? DeletionProtection { get; set; }

        /// <summary>
        /// The dimensions of the vectors to be inserted in the index
        /// </summary>
        [Input("dimension")]
        public Input<int>? Dimension { get; set; }

        /// <summary>
        /// Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
        /// </summary>
        [Input("embed")]
        public Input<Inputs.IndexEmbedGetArgs>? Embed { get; set; }

        /// <summary>
        /// The URL address where the index is hosted.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        /// <summary>
        /// The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If the 'vector_type' is 'sparse', the metric must be 'dotproduct'. If the VectorType is dense, the metric defaults to 'cosine'.
        /// </summary>
        [Input("metric")]
        public Input<string>? Metric { get; set; }

        /// <summary>
        /// The name of the index to be created. The maximum length is 45 characters.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Spec
        /// </summary>
        [Input("spec")]
        public Input<Inputs.IndexSpecGetArgs>? Spec { get; set; }

        /// <summary>
        /// Status
        /// </summary>
        [Input("status")]
        public Input<Inputs.IndexStatusGetArgs>? Status { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Custom user tags added to an index. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '', or '-'. Values must be alphanumeric, ';', '@', '', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        [Input("timeouts")]
        public Input<Inputs.IndexTimeoutsGetArgs>? Timeouts { get; set; }

        /// <summary>
        /// The index vector type. You can use 'dense' or 'sparse'. If 'dense', the vector dimension must be specified. If 'sparse', the vector dimension should not be specified.
        /// </summary>
        [Input("vectorType")]
        public Input<string>? VectorType { get; set; }

        public IndexState()
        {
        }
        public static new IndexState Empty => new IndexState();
    }
}
