// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone
{
    public static class LookupPineconeCollection
    {
        /// <summary>
        /// The result of a get operation on a Pinecone collection.
        /// </summary>
        public static Task<LookupPineconeCollectionResult> InvokeAsync(LookupPineconeCollectionArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<LookupPineconeCollectionResult>("pinecone:index:lookupPineconeCollection", args ?? new LookupPineconeCollectionArgs(), options.WithDefaults());

        /// <summary>
        /// The result of a get operation on a Pinecone collection.
        /// </summary>
        public static Output<LookupPineconeCollectionResult> Invoke(LookupPineconeCollectionInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<LookupPineconeCollectionResult>("pinecone:index:lookupPineconeCollection", args ?? new LookupPineconeCollectionInvokeArgs(), options.WithDefaults());
    }


    public sealed class LookupPineconeCollectionArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the Pinecone collection.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public LookupPineconeCollectionArgs()
        {
        }
        public static new LookupPineconeCollectionArgs Empty => new LookupPineconeCollectionArgs();
    }

    public sealed class LookupPineconeCollectionInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the Pinecone collection.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public LookupPineconeCollectionInvokeArgs()
        {
        }
        public static new LookupPineconeCollectionInvokeArgs Empty => new LookupPineconeCollectionInvokeArgs();
    }


    [OutputType]
    public sealed class LookupPineconeCollectionResult
    {
        /// <summary>
        /// The dimension of the vectors stored in each record held in the collection.
        /// </summary>
        public readonly int Dimension;
        /// <summary>
        /// The environment where the collection is hosted.
        /// </summary>
        public readonly string Environment;
        /// <summary>
        /// The name of the collection to be created.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The size of the collection in bytes.
        /// </summary>
        public readonly int Size;
        /// <summary>
        /// The name of the index to be used as the source for the collection.
        /// </summary>
        public readonly string Source;
        /// <summary>
        /// The number of records stored in the collection.
        /// </summary>
        public readonly int VectorCount;

        [OutputConstructor]
        private LookupPineconeCollectionResult(
            int dimension,

            string environment,

            string name,

            int size,

            string source,

            int vectorCount)
        {
            Dimension = dimension;
            Environment = environment;
            Name = name;
            Size = size;
            Source = source;
            VectorCount = vectorCount;
        }
    }
}
