// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pinecone

import (
	"context"
	"reflect"

	"errors"
	"github.com/pinecone-io/pulumi-pinecone/sdk/go/pinecone/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The `Collection` resource lets you create and manage collections in Pinecone. Learn more about collections in the docs.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-terraform-provider/sdks/go/pinecone/v2/pinecone"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			test, err := pinecone.NewIndex(ctx, "test", &pinecone.IndexArgs{
//				Name:      pulumi.String("tftestindex"),
//				Dimension: pulumi.Float64(10),
//				Spec: &pinecone.IndexSpecArgs{
//					Pod: &pinecone.IndexSpecPodArgs{
//						Environment: pulumi.String("us-west4-gcp"),
//						PodType:     pulumi.String("s1.x1"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = pinecone.NewCollection(ctx, "test", &pinecone.CollectionArgs{
//				Name:   pulumi.String("tftestcollection"),
//				Source: test.Name,
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type Collection struct {
	pulumi.CustomResourceState

	// The dimension of the vectors stored in each record held in the collection.
	Dimension pulumi.IntOutput `pulumi:"dimension"`
	// The environment where the collection is hosted.
	Environment pulumi.StringOutput `pulumi:"environment"`
	// The name of the collection.
	Name pulumi.StringOutput `pulumi:"name"`
	// The size of the collection in bytes.
	Size pulumi.IntOutput `pulumi:"size"`
	// The name of the source index to be used as the source for the collection.
	Source pulumi.StringOutput `pulumi:"source"`
	// The status of the collection.
	Status   pulumi.StringOutput         `pulumi:"status"`
	Timeouts CollectionTimeoutsPtrOutput `pulumi:"timeouts"`
	// The number of records stored in the collection.
	VectorCount pulumi.IntOutput `pulumi:"vectorCount"`
}

// NewCollection registers a new resource with the given unique name, arguments, and options.
func NewCollection(ctx *pulumi.Context,
	name string, args *CollectionArgs, opts ...pulumi.ResourceOption) (*Collection, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Source == nil {
		return nil, errors.New("invalid value for required argument 'Source'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Collection
	err := ctx.RegisterResource("pinecone:index/collection:Collection", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCollection gets an existing Collection resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCollection(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CollectionState, opts ...pulumi.ResourceOption) (*Collection, error) {
	var resource Collection
	err := ctx.ReadResource("pinecone:index/collection:Collection", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Collection resources.
type collectionState struct {
	// The dimension of the vectors stored in each record held in the collection.
	Dimension *int `pulumi:"dimension"`
	// The environment where the collection is hosted.
	Environment *string `pulumi:"environment"`
	// The name of the collection.
	Name *string `pulumi:"name"`
	// The size of the collection in bytes.
	Size *int `pulumi:"size"`
	// The name of the source index to be used as the source for the collection.
	Source *string `pulumi:"source"`
	// The status of the collection.
	Status   *string             `pulumi:"status"`
	Timeouts *CollectionTimeouts `pulumi:"timeouts"`
	// The number of records stored in the collection.
	VectorCount *int `pulumi:"vectorCount"`
}

type CollectionState struct {
	// The dimension of the vectors stored in each record held in the collection.
	Dimension pulumi.IntPtrInput
	// The environment where the collection is hosted.
	Environment pulumi.StringPtrInput
	// The name of the collection.
	Name pulumi.StringPtrInput
	// The size of the collection in bytes.
	Size pulumi.IntPtrInput
	// The name of the source index to be used as the source for the collection.
	Source pulumi.StringPtrInput
	// The status of the collection.
	Status   pulumi.StringPtrInput
	Timeouts CollectionTimeoutsPtrInput
	// The number of records stored in the collection.
	VectorCount pulumi.IntPtrInput
}

func (CollectionState) ElementType() reflect.Type {
	return reflect.TypeOf((*collectionState)(nil)).Elem()
}

type collectionArgs struct {
	// The dimension of the vectors stored in each record held in the collection.
	Dimension *int `pulumi:"dimension"`
	// The name of the collection.
	Name *string `pulumi:"name"`
	// The size of the collection in bytes.
	Size *int `pulumi:"size"`
	// The name of the source index to be used as the source for the collection.
	Source   string              `pulumi:"source"`
	Timeouts *CollectionTimeouts `pulumi:"timeouts"`
	// The number of records stored in the collection.
	VectorCount *int `pulumi:"vectorCount"`
}

// The set of arguments for constructing a Collection resource.
type CollectionArgs struct {
	// The dimension of the vectors stored in each record held in the collection.
	Dimension pulumi.IntPtrInput
	// The name of the collection.
	Name pulumi.StringPtrInput
	// The size of the collection in bytes.
	Size pulumi.IntPtrInput
	// The name of the source index to be used as the source for the collection.
	Source   pulumi.StringInput
	Timeouts CollectionTimeoutsPtrInput
	// The number of records stored in the collection.
	VectorCount pulumi.IntPtrInput
}

func (CollectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*collectionArgs)(nil)).Elem()
}

type CollectionInput interface {
	pulumi.Input

	ToCollectionOutput() CollectionOutput
	ToCollectionOutputWithContext(ctx context.Context) CollectionOutput
}

func (*Collection) ElementType() reflect.Type {
	return reflect.TypeOf((**Collection)(nil)).Elem()
}

func (i *Collection) ToCollectionOutput() CollectionOutput {
	return i.ToCollectionOutputWithContext(context.Background())
}

func (i *Collection) ToCollectionOutputWithContext(ctx context.Context) CollectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CollectionOutput)
}

// CollectionArrayInput is an input type that accepts CollectionArray and CollectionArrayOutput values.
// You can construct a concrete instance of `CollectionArrayInput` via:
//
//	CollectionArray{ CollectionArgs{...} }
type CollectionArrayInput interface {
	pulumi.Input

	ToCollectionArrayOutput() CollectionArrayOutput
	ToCollectionArrayOutputWithContext(context.Context) CollectionArrayOutput
}

type CollectionArray []CollectionInput

func (CollectionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Collection)(nil)).Elem()
}

func (i CollectionArray) ToCollectionArrayOutput() CollectionArrayOutput {
	return i.ToCollectionArrayOutputWithContext(context.Background())
}

func (i CollectionArray) ToCollectionArrayOutputWithContext(ctx context.Context) CollectionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CollectionArrayOutput)
}

// CollectionMapInput is an input type that accepts CollectionMap and CollectionMapOutput values.
// You can construct a concrete instance of `CollectionMapInput` via:
//
//	CollectionMap{ "key": CollectionArgs{...} }
type CollectionMapInput interface {
	pulumi.Input

	ToCollectionMapOutput() CollectionMapOutput
	ToCollectionMapOutputWithContext(context.Context) CollectionMapOutput
}

type CollectionMap map[string]CollectionInput

func (CollectionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Collection)(nil)).Elem()
}

func (i CollectionMap) ToCollectionMapOutput() CollectionMapOutput {
	return i.ToCollectionMapOutputWithContext(context.Background())
}

func (i CollectionMap) ToCollectionMapOutputWithContext(ctx context.Context) CollectionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CollectionMapOutput)
}

type CollectionOutput struct{ *pulumi.OutputState }

func (CollectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Collection)(nil)).Elem()
}

func (o CollectionOutput) ToCollectionOutput() CollectionOutput {
	return o
}

func (o CollectionOutput) ToCollectionOutputWithContext(ctx context.Context) CollectionOutput {
	return o
}

// The dimension of the vectors stored in each record held in the collection.
func (o CollectionOutput) Dimension() pulumi.IntOutput {
	return o.ApplyT(func(v *Collection) pulumi.IntOutput { return v.Dimension }).(pulumi.IntOutput)
}

// The environment where the collection is hosted.
func (o CollectionOutput) Environment() pulumi.StringOutput {
	return o.ApplyT(func(v *Collection) pulumi.StringOutput { return v.Environment }).(pulumi.StringOutput)
}

// The name of the collection.
func (o CollectionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Collection) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The size of the collection in bytes.
func (o CollectionOutput) Size() pulumi.IntOutput {
	return o.ApplyT(func(v *Collection) pulumi.IntOutput { return v.Size }).(pulumi.IntOutput)
}

// The name of the source index to be used as the source for the collection.
func (o CollectionOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v *Collection) pulumi.StringOutput { return v.Source }).(pulumi.StringOutput)
}

// The status of the collection.
func (o CollectionOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Collection) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o CollectionOutput) Timeouts() CollectionTimeoutsPtrOutput {
	return o.ApplyT(func(v *Collection) CollectionTimeoutsPtrOutput { return v.Timeouts }).(CollectionTimeoutsPtrOutput)
}

// The number of records stored in the collection.
func (o CollectionOutput) VectorCount() pulumi.IntOutput {
	return o.ApplyT(func(v *Collection) pulumi.IntOutput { return v.VectorCount }).(pulumi.IntOutput)
}

type CollectionArrayOutput struct{ *pulumi.OutputState }

func (CollectionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Collection)(nil)).Elem()
}

func (o CollectionArrayOutput) ToCollectionArrayOutput() CollectionArrayOutput {
	return o
}

func (o CollectionArrayOutput) ToCollectionArrayOutputWithContext(ctx context.Context) CollectionArrayOutput {
	return o
}

func (o CollectionArrayOutput) Index(i pulumi.IntInput) CollectionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Collection {
		return vs[0].([]*Collection)[vs[1].(int)]
	}).(CollectionOutput)
}

type CollectionMapOutput struct{ *pulumi.OutputState }

func (CollectionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Collection)(nil)).Elem()
}

func (o CollectionMapOutput) ToCollectionMapOutput() CollectionMapOutput {
	return o
}

func (o CollectionMapOutput) ToCollectionMapOutputWithContext(ctx context.Context) CollectionMapOutput {
	return o
}

func (o CollectionMapOutput) MapIndex(k pulumi.StringInput) CollectionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Collection {
		return vs[0].(map[string]*Collection)[vs[1].(string)]
	}).(CollectionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CollectionInput)(nil)).Elem(), &Collection{})
	pulumi.RegisterInputType(reflect.TypeOf((*CollectionArrayInput)(nil)).Elem(), CollectionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CollectionMapInput)(nil)).Elem(), CollectionMap{})
	pulumi.RegisterOutputType(CollectionOutput{})
	pulumi.RegisterOutputType(CollectionArrayOutput{})
	pulumi.RegisterOutputType(CollectionMapOutput{})
}
