// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pinecone

import (
	"context"
	"reflect"

	"github.com/pinecone-io/pulumi-pinecone/sdk/v2/go/pinecone/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Index data source
func Get(ctx *pulumi.Context, args *GetArgs, opts ...pulumi.InvokeOption) (*GetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetResult
	err := ctx.Invoke("pinecone:index/get:get", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking get.
type GetArgs struct {
	// Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
	Embed *GetEmbed `pulumi:"embed"`
	// Index name
	Name   string     `pulumi:"name"`
	Spec   *GetSpec   `pulumi:"spec"`
	Status *GetStatus `pulumi:"status"`
}

// A collection of values returned by get.
type GetResult struct {
	DeletionProtection string `pulumi:"deletionProtection"`
	Dimension          int    `pulumi:"dimension"`
	// Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
	Embed  GetEmbed `pulumi:"embed"`
	Host   string   `pulumi:"host"`
	Id     string   `pulumi:"id"`
	Metric string   `pulumi:"metric"`
	// Index name
	Name       string            `pulumi:"name"`
	Spec       GetSpec           `pulumi:"spec"`
	Status     GetStatus         `pulumi:"status"`
	Tags       map[string]string `pulumi:"tags"`
	VectorType string            `pulumi:"vectorType"`
}

func GetOutput(ctx *pulumi.Context, args GetOutputArgs, opts ...pulumi.InvokeOption) GetResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetResultOutput, error) {
			args := v.(GetArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("pinecone:index/get:get", args, GetResultOutput{}, options).(GetResultOutput), nil
		}).(GetResultOutput)
}

// A collection of arguments for invoking get.
type GetOutputArgs struct {
	// Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
	Embed GetEmbedPtrInput `pulumi:"embed"`
	// Index name
	Name   pulumi.StringInput `pulumi:"name"`
	Spec   GetSpecPtrInput    `pulumi:"spec"`
	Status GetStatusPtrInput  `pulumi:"status"`
}

func (GetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetArgs)(nil)).Elem()
}

// A collection of values returned by get.
type GetResultOutput struct{ *pulumi.OutputState }

func (GetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResult)(nil)).Elem()
}

func (o GetResultOutput) ToGetResultOutput() GetResultOutput {
	return o
}

func (o GetResultOutput) ToGetResultOutputWithContext(ctx context.Context) GetResultOutput {
	return o
}

func (o GetResultOutput) DeletionProtection() pulumi.StringOutput {
	return o.ApplyT(func(v GetResult) string { return v.DeletionProtection }).(pulumi.StringOutput)
}

func (o GetResultOutput) Dimension() pulumi.IntOutput {
	return o.ApplyT(func(v GetResult) int { return v.Dimension }).(pulumi.IntOutput)
}

// Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
func (o GetResultOutput) Embed() GetEmbedOutput {
	return o.ApplyT(func(v GetResult) GetEmbed { return v.Embed }).(GetEmbedOutput)
}

func (o GetResultOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func(v GetResult) string { return v.Host }).(pulumi.StringOutput)
}

func (o GetResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetResultOutput) Metric() pulumi.StringOutput {
	return o.ApplyT(func(v GetResult) string { return v.Metric }).(pulumi.StringOutput)
}

// Index name
func (o GetResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetResultOutput) Spec() GetSpecOutput {
	return o.ApplyT(func(v GetResult) GetSpec { return v.Spec }).(GetSpecOutput)
}

func (o GetResultOutput) Status() GetStatusOutput {
	return o.ApplyT(func(v GetResult) GetStatus { return v.Status }).(GetStatusOutput)
}

func (o GetResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

func (o GetResultOutput) VectorType() pulumi.StringOutput {
	return o.ApplyT(func(v GetResult) string { return v.VectorType }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetResultOutput{})
}
