// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pinecone

import (
	"context"
	"reflect"

	"github.com/pinecone-io/pulumi-pinecone/sdk/v2/go/pinecone/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Collections data source
func GetCollections(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetCollectionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetCollectionsResult
	err := ctx.Invoke("pinecone:index/getCollections:getCollections", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getCollections.
type GetCollectionsResult struct {
	// List of the collections in your project
	Collections []GetCollectionsCollection `pulumi:"collections"`
	// Collections identifier
	Id string `pulumi:"id"`
}

func GetCollectionsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetCollectionsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetCollectionsResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("pinecone:index/getCollections:getCollections", nil, GetCollectionsResultOutput{}, options).(GetCollectionsResultOutput), nil
	}).(GetCollectionsResultOutput)
}

// A collection of values returned by getCollections.
type GetCollectionsResultOutput struct{ *pulumi.OutputState }

func (GetCollectionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCollectionsResult)(nil)).Elem()
}

func (o GetCollectionsResultOutput) ToGetCollectionsResultOutput() GetCollectionsResultOutput {
	return o
}

func (o GetCollectionsResultOutput) ToGetCollectionsResultOutputWithContext(ctx context.Context) GetCollectionsResultOutput {
	return o
}

// List of the collections in your project
func (o GetCollectionsResultOutput) Collections() GetCollectionsCollectionArrayOutput {
	return o.ApplyT(func(v GetCollectionsResult) []GetCollectionsCollection { return v.Collections }).(GetCollectionsCollectionArrayOutput)
}

// Collections identifier
func (o GetCollectionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCollectionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCollectionsResultOutput{})
}
