// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pinecone

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"internal"
)

type PineconeIndex struct {
	pulumi.CustomResourceState

	IndexName pulumi.StringOutput `pulumi:"indexName"`
}

// NewPineconeIndex registers a new resource with the given unique name, arguments, and options.
func NewPineconeIndex(ctx *pulumi.Context,
	name string, args *PineconeIndexArgs, opts ...pulumi.ResourceOption) (*PineconeIndex, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Dimension == nil {
		return nil, errors.New("invalid value for required argument 'Dimension'")
	}
	if args.Metric == nil {
		return nil, errors.New("invalid value for required argument 'Metric'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.PodType == nil {
		return nil, errors.New("invalid value for required argument 'PodType'")
	}
	if args.Pods == nil {
		return nil, errors.New("invalid value for required argument 'Pods'")
	}
	if args.Replicas == nil {
		return nil, errors.New("invalid value for required argument 'Replicas'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PineconeIndex
	err := ctx.RegisterResource("pinecone:index:PineconeIndex", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPineconeIndex gets an existing PineconeIndex resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPineconeIndex(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PineconeIndexState, opts ...pulumi.ResourceOption) (*PineconeIndex, error) {
	var resource PineconeIndex
	err := ctx.ReadResource("pinecone:index:PineconeIndex", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PineconeIndex resources.
type pineconeIndexState struct {
}

type PineconeIndexState struct {
}

func (PineconeIndexState) ElementType() reflect.Type {
	return reflect.TypeOf((*pineconeIndexState)(nil)).Elem()
}

type pineconeIndexArgs struct {
	// The dimensions of the vectors in the index.
	Dimension int `pulumi:"dimension"`
	// The metric used to compute the distance between vectors.
	Metric string `pulumi:"metric"`
	// The name of the Pinecone index.
	Name string `pulumi:"name"`
	// The type of pods to use for the index.
	PodType string `pulumi:"podType"`
	// The number of pods to use for the index.
	Pods int `pulumi:"pods"`
	// The number of replicas to use for the index.
	Replicas int `pulumi:"replicas"`
}

// The set of arguments for constructing a PineconeIndex resource.
type PineconeIndexArgs struct {
	// The dimensions of the vectors in the index.
	Dimension pulumi.IntInput
	// The metric used to compute the distance between vectors.
	Metric pulumi.StringInput
	// The name of the Pinecone index.
	Name pulumi.StringInput
	// The type of pods to use for the index.
	PodType pulumi.StringInput
	// The number of pods to use for the index.
	Pods pulumi.IntInput
	// The number of replicas to use for the index.
	Replicas pulumi.IntInput
}

func (PineconeIndexArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*pineconeIndexArgs)(nil)).Elem()
}

type PineconeIndexInput interface {
	pulumi.Input

	ToPineconeIndexOutput() PineconeIndexOutput
	ToPineconeIndexOutputWithContext(ctx context.Context) PineconeIndexOutput
}

func (*PineconeIndex) ElementType() reflect.Type {
	return reflect.TypeOf((**PineconeIndex)(nil)).Elem()
}

func (i *PineconeIndex) ToPineconeIndexOutput() PineconeIndexOutput {
	return i.ToPineconeIndexOutputWithContext(context.Background())
}

func (i *PineconeIndex) ToPineconeIndexOutputWithContext(ctx context.Context) PineconeIndexOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PineconeIndexOutput)
}

type PineconeIndexOutput struct{ *pulumi.OutputState }

func (PineconeIndexOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PineconeIndex)(nil)).Elem()
}

func (o PineconeIndexOutput) ToPineconeIndexOutput() PineconeIndexOutput {
	return o
}

func (o PineconeIndexOutput) ToPineconeIndexOutputWithContext(ctx context.Context) PineconeIndexOutput {
	return o
}

func (o PineconeIndexOutput) IndexName() pulumi.StringOutput {
	return o.ApplyT(func(v *PineconeIndex) pulumi.StringOutput { return v.IndexName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PineconeIndexInput)(nil)).Elem(), &PineconeIndex{})
	pulumi.RegisterOutputType(PineconeIndexOutput{})
}
