// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const IndexMetric = {
    Dotproduct: "dotproduct",
    Cosine: "cosine",
    Euclidean: "euclidean",
} as const;

export type IndexMetric = (typeof IndexMetric)[keyof typeof IndexMetric];

export const ServerlessSpecCloud = {
    Aws: "aws",
    Azure: "azure",
    Gcp: "gcp",
} as const;

export type ServerlessSpecCloud = (typeof ServerlessSpecCloud)[keyof typeof ServerlessSpecCloud];
