// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("pinecone");

/**
 * The API token for Pinecone.
 */
export declare const apiToken: string | undefined;
Object.defineProperty(exports, "apiToken", {
    get() {
        return __config.get("apiToken");
    },
    enumerable: true,
});

/**
 * The environment for the Pinecone API.
 */
export declare const pineconeEnv: string | undefined;
Object.defineProperty(exports, "pineconeEnv", {
    get() {
        return __config.get("pineconeEnv");
    },
    enumerable: true,
});

