// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Outputs
{

    [OutputType]
    public sealed class GetCollectionsCollectionResult
    {
        /// <summary>
        /// The dimension of the vectors stored in each record held in the collection.
        /// </summary>
        public readonly int Dimension;
        /// <summary>
        /// The environment where the collection is hosted.
        /// </summary>
        public readonly string Environment;
        /// <summary>
        /// The name of the collection.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The size of the collection in bytes.
        /// </summary>
        public readonly int Size;
        /// <summary>
        /// The status of the collection.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// The number of records stored in the collection.
        /// </summary>
        public readonly int VectorCount;

        [OutputConstructor]
        private GetCollectionsCollectionResult(
            int dimension,

            string environment,

            string name,

            int size,

            string status,

            int vectorCount)
        {
            Dimension = dimension;
            Environment = environment;
            Name = name;
            Size = size;
            Status = status;
            VectorCount = vectorCount;
        }
    }
}
