// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Outputs
{

    [OutputType]
    public sealed class GetEsIndexSpecPodResult
    {
        /// <summary>
        /// The environment where the index is hosted.
        /// </summary>
        public readonly string Environment;
        /// <summary>
        /// Configuration for the behavior of Pinecone's internal metadata index. By default, all metadata is indexed; when metadata*config is present, only specified metadata fields are indexed. These configurations are only valid for use with pod-based indexes.
        /// </summary>
        public readonly Outputs.GetEsIndexSpecPodMetadataConfigResult MetadataConfig;
        /// <summary>
        /// The type of pod to use. One of s1, p1, or p2 appended with . and one of x1, x2, x4, or x8.
        /// </summary>
        public readonly string PodType;
        /// <summary>
        /// The number of pods to be used in the index. This should be equal to shards x replicas.'
        /// </summary>
        public readonly int Pods;
        /// <summary>
        /// The number of replicas. Replicas duplicate your index. They provide higher availability and throughput. Replicas can be scaled up or down as your needs change.
        /// </summary>
        public readonly int Replicas;
        /// <summary>
        /// The number of shards. Shards split your data across multiple pods so you can fit more data into an index.
        /// </summary>
        public readonly int Shards;
        /// <summary>
        /// The name of the collection to create an index from.
        /// </summary>
        public readonly string SourceCollection;

        [OutputConstructor]
        private GetEsIndexSpecPodResult(
            string environment,

            Outputs.GetEsIndexSpecPodMetadataConfigResult metadataConfig,

            string podType,

            int pods,

            int replicas,

            int shards,

            string sourceCollection)
        {
            Environment = environment;
            MetadataConfig = metadataConfig;
            PodType = podType;
            Pods = pods;
            Replicas = replicas;
            Shards = shards;
            SourceCollection = sourceCollection;
        }
    }
}
