// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Outputs
{

    [OutputType]
    public sealed class GetEsIndexResult
    {
        /// <summary>
        /// Index deletion protection configuration
        /// </summary>
        public readonly string DeletionProtection;
        /// <summary>
        /// Index dimension
        /// </summary>
        public readonly int Dimension;
        /// <summary>
        /// Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
        /// </summary>
        public readonly Outputs.GetEsIndexEmbedResult Embed;
        /// <summary>
        /// The URL address where the index is hosted.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// Index metric
        /// </summary>
        public readonly string Metric;
        /// <summary>
        /// Index name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Spec
        /// </summary>
        public readonly Outputs.GetEsIndexSpecResult Spec;
        /// <summary>
        /// Configuration for the behavior of Pinecone's internal metadata index. By default, all metadata is indexed; when MetadataConfig is present, only specified metadata fields are indexed. To specify metadata fields to index, provide an array of the following form: [ExampleMetadataField]
        /// </summary>
        public readonly Outputs.GetEsIndexStatusResult Status;
        /// <summary>
        /// Custom user tags added to an index. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '', or '-'. Values must be alphanumeric, ';', '@', '', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Tags;
        /// <summary>
        /// Index vector type
        /// </summary>
        public readonly string VectorType;

        [OutputConstructor]
        private GetEsIndexResult(
            string deletionProtection,

            int dimension,

            Outputs.GetEsIndexEmbedResult embed,

            string host,

            string metric,

            string name,

            Outputs.GetEsIndexSpecResult spec,

            Outputs.GetEsIndexStatusResult status,

            ImmutableDictionary<string, string> tags,

            string vectorType)
        {
            DeletionProtection = deletionProtection;
            Dimension = dimension;
            Embed = embed;
            Host = host;
            Metric = metric;
            Name = name;
            Spec = spec;
            Status = status;
            Tags = tags;
            VectorType = vectorType;
        }
    }
}
