// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Outputs
{

    [OutputType]
    public sealed class GetEsIndexStatusResult
    {
        /// <summary>
        /// Ready.
        /// </summary>
        public readonly bool Ready;
        /// <summary>
        /// Initializing InitializationFailed ScalingUp ScalingDown ScalingUpPodSize ScalingDownPodSize Upgrading Terminating Ready
        /// </summary>
        public readonly string State;

        [OutputConstructor]
        private GetEsIndexStatusResult(
            bool ready,

            string state)
        {
            Ready = ready;
            State = state;
        }
    }
}
