// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Outputs
{

    [OutputType]
    public sealed class GetEsIndexSpecServerlessResult
    {
        /// <summary>
        /// Ready.
        /// </summary>
        public readonly string Cloud;
        /// <summary>
        /// Initializing InitializationFailed ScalingUp ScalingDown ScalingUpPodSize ScalingDownPodSize Upgrading Terminating Ready
        /// </summary>
        public readonly string Region;

        [OutputConstructor]
        private GetEsIndexSpecServerlessResult(
            string cloud,

            string region)
        {
            Cloud = cloud;
            Region = region;
        }
    }
}
