// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Outputs
{

    [OutputType]
    public sealed class GetEmbedResult
    {
        /// <summary>
        /// The dimension of the embedding model, specifying the size of the output vector.
        /// </summary>
        public readonly int Dimension;
        /// <summary>
        /// Identifies the name of the text field from your document model that will be embedded.
        /// </summary>
        public readonly ImmutableDictionary<string, string> FieldMap;
        /// <summary>
        /// The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If the 'vector*type' is 'sparse', the metric must be 'dotproduct'. If the vector*type is dense, the metric defaults to 'cosine'.
        /// </summary>
        public readonly string Metric;
        /// <summary>
        /// the name of the embedding model to use for the index.
        /// </summary>
        public readonly string Model;
        /// <summary>
        /// The read parameters for the embedding model.
        /// </summary>
        public readonly ImmutableDictionary<string, string> ReadParameters;
        /// <summary>
        /// The index vector type associated with the model. If 'dense', the vector dimension must be specified. If 'sparse', the vector dimension will be nil.
        /// </summary>
        public readonly string VectorType;
        /// <summary>
        /// The write parameters for the embedding model.
        /// </summary>
        public readonly ImmutableDictionary<string, string> WriteParameters;

        [OutputConstructor]
        private GetEmbedResult(
            int dimension,

            ImmutableDictionary<string, string> fieldMap,

            string metric,

            string model,

            ImmutableDictionary<string, string> readParameters,

            string vectorType,

            ImmutableDictionary<string, string> writeParameters)
        {
            Dimension = dimension;
            FieldMap = fieldMap;
            Metric = metric;
            Model = model;
            ReadParameters = readParameters;
            VectorType = vectorType;
            WriteParameters = writeParameters;
        }
    }
}
