// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Outputs
{

    [OutputType]
    public sealed class GetSpecResult
    {
        /// <summary>
        /// Configuration needed to deploy a pod-based index.
        /// </summary>
        public readonly Outputs.GetSpecPodResult Pod;
        /// <summary>
        /// Configuration needed to deploy a serverless index.
        /// </summary>
        public readonly Outputs.GetSpecServerlessResult Serverless;

        [OutputConstructor]
        private GetSpecResult(
            Outputs.GetSpecPodResult pod,

            Outputs.GetSpecServerlessResult serverless)
        {
            Pod = pod;
            Serverless = serverless;
        }
    }
}
