// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Outputs
{

    [OutputType]
    public sealed class MetaDataConfig
    {
        public readonly ImmutableArray<string> Indexed;

        [OutputConstructor]
        private MetaDataConfig(ImmutableArray<string> indexed)
        {
            Indexed = indexed;
        }
    }
}
