// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface MetaDataConfigArgs {
    indexed?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface PineconePodSpecArgs {
    environment: pulumi.Input<string>;
    metaDataConfig?: pulumi.Input<inputs.MetaDataConfigArgs>;
    podType: pulumi.Input<string>;
    pods?: pulumi.Input<number>;
    replicas: pulumi.Input<number>;
    shards?: pulumi.Input<number>;
    sourceCollection?: pulumi.Input<string>;
}

export interface PineconeServerlessSpecArgs {
    /**
     * he public cloud where you would like your index hosted
     */
    cloud: pulumi.Input<enums.ServerlessSpecCloud>;
    /**
     * The region where you would like your index to be created. Different cloud providers have different regions available.
     */
    region: pulumi.Input<string>;
}

export interface PineconeSpecArgs {
    /**
     * Configuration needed to deploy a pod index.
     */
    pod?: pulumi.Input<inputs.PineconePodSpecArgs>;
    /**
     * Configuration needed to deploy a serverless index.
     */
    serverless?: pulumi.Input<inputs.PineconeServerlessSpecArgs>;
}
