// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface MetaDataConfigArgs {
    /**
     *  Indexed By default, all metadata is indexed; to change this behavior, use this property to specify an array of metadata fields which should be indexed.
     */
    indexed?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface PineconePodSpecArgs {
    /**
     * The environment where the index is hosted.
     */
    environment: pulumi.Input<string>;
    /**
     * Configuration for the behavior of Pinecone's internal metadata index.
     */
    metaDataConfig?: pulumi.Input<inputs.MetaDataConfigArgs>;
    /**
     * The type of pod to use. One of `s1`, `p1`, or `p2` appended with `.` and one of `x1`, `x2`, `x4`, or `x8`.
     */
    podType: pulumi.Input<string>;
    /**
     * The number of pods to be used in the index. This should be equal to `shards` x `replicas`.
     */
    pods?: pulumi.Input<number>;
    /**
     * The number of replicas. Replicas duplicate your index. They provide higher availability and throughput. Replicas can be scaled up or down as your needs change.
     */
    replicas: pulumi.Input<number>;
    /**
     * The number of shards. Shards split your data across multiple pods so you can fit more data into an index.
     */
    shards?: pulumi.Input<number>;
    /**
     * The name of the collection to be used as the source for the index.
     */
    sourceCollection?: pulumi.Input<string>;
}

export interface PineconeServerlessSpecArgs {
    /**
     * The public cloud where you would like your index hosted.
     */
    cloud: pulumi.Input<enums.ServerlessSpecCloud>;
    /**
     * The region where you would like your index to be created. Different cloud providers have different regions available.
     */
    region: pulumi.Input<string>;
}

export interface PineconeSpecArgs {
    /**
     * Configuration needed to deploy a pod index.
     */
    pod?: pulumi.Input<inputs.PineconePodSpecArgs>;
    /**
     * Configuration needed to deploy a serverless index.
     */
    serverless?: pulumi.Input<inputs.PineconeServerlessSpecArgs>;
}
