# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .pinecone_index import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_pinecone.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_pinecone.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pinecone",
  "mod": "index",
  "fqn": "pulumi_pinecone",
  "classes": {
   "pinecone:index:PineconeIndex": "PineconeIndex"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pinecone",
  "token": "pulumi:providers:pinecone",
  "fqn": "pulumi_pinecone",
  "class": "Provider"
 }
]
"""
)
