// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Inputs
{

    public sealed class GetEmbedInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The dimension of the embedding model, specifying the size of the output vector.
        /// </summary>
        [Input("dimension", required: true)]
        public Input<int> Dimension { get; set; } = null!;

        [Input("fieldMap", required: true)]
        private InputMap<string>? _fieldMap;

        /// <summary>
        /// Identifies the name of the text field from your document model that will be embedded.
        /// </summary>
        public InputMap<string> FieldMap
        {
            get => _fieldMap ?? (_fieldMap = new InputMap<string>());
            set => _fieldMap = value;
        }

        /// <summary>
        /// The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If the 'vector*type' is 'sparse', the metric must be 'dotproduct'. If the vector*type is dense, the metric defaults to 'cosine'.
        /// </summary>
        [Input("metric", required: true)]
        public Input<string> Metric { get; set; } = null!;

        /// <summary>
        /// the name of the embedding model to use for the index.
        /// </summary>
        [Input("model", required: true)]
        public Input<string> Model { get; set; } = null!;

        [Input("readParameters", required: true)]
        private InputMap<string>? _readParameters;

        /// <summary>
        /// The read parameters for the embedding model.
        /// </summary>
        public InputMap<string> ReadParameters
        {
            get => _readParameters ?? (_readParameters = new InputMap<string>());
            set => _readParameters = value;
        }

        /// <summary>
        /// The index vector type associated with the model. If 'dense', the vector dimension must be specified. If 'sparse', the vector dimension will be nil.
        /// </summary>
        [Input("vectorType", required: true)]
        public Input<string> VectorType { get; set; } = null!;

        [Input("writeParameters", required: true)]
        private InputMap<string>? _writeParameters;

        /// <summary>
        /// The write parameters for the embedding model.
        /// </summary>
        public InputMap<string> WriteParameters
        {
            get => _writeParameters ?? (_writeParameters = new InputMap<string>());
            set => _writeParameters = value;
        }

        public GetEmbedInputArgs()
        {
        }
        public static new GetEmbedInputArgs Empty => new GetEmbedInputArgs();
    }
}
