// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Inputs
{

    public sealed class GetSpecPodInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The environment where the index is hosted.
        /// </summary>
        [Input("environment", required: true)]
        public Input<string> Environment { get; set; } = null!;

        /// <summary>
        /// Configuration for the behavior of Pinecone's internal metadata index. By default, all metadata is indexed; when metadata*config is present, only specified metadata fields are indexed. These configurations are only valid for use with pod-based indexes.
        /// </summary>
        [Input("metadataConfig", required: true)]
        public Input<Inputs.GetSpecPodMetadataConfigInputArgs> MetadataConfig { get; set; } = null!;

        /// <summary>
        /// The type of pod to use. One of s1, p1, or p2 appended with . and one of x1, x2, x4, or x8.
        /// </summary>
        [Input("podType", required: true)]
        public Input<string> PodType { get; set; } = null!;

        /// <summary>
        /// The number of pods to be used in the index. This should be equal to shards x replicas.'
        /// </summary>
        [Input("pods", required: true)]
        public Input<int> Pods { get; set; } = null!;

        /// <summary>
        /// The number of replicas. Replicas duplicate your index. They provide higher availability and throughput. Replicas can be scaled up or down as your needs change.
        /// </summary>
        [Input("replicas", required: true)]
        public Input<int> Replicas { get; set; } = null!;

        /// <summary>
        /// The number of shards. Shards split your data across multiple pods so you can fit more data into an index.
        /// </summary>
        [Input("shards", required: true)]
        public Input<int> Shards { get; set; } = null!;

        /// <summary>
        /// The name of the collection to create an index from.
        /// </summary>
        [Input("sourceCollection", required: true)]
        public Input<string> SourceCollection { get; set; } = null!;

        public GetSpecPodInputArgs()
        {
        }
        public static new GetSpecPodInputArgs Empty => new GetSpecPodInputArgs();
    }
}
