// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Inputs
{

    public sealed class GetSpecPodMetadataConfigArgs : global::Pulumi.InvokeArgs
    {
        [Input("indexeds", required: true)]
        private List<string>? _indexeds;

        /// <summary>
        /// The indexed fields.
        /// </summary>
        public List<string> Indexeds
        {
            get => _indexeds ?? (_indexeds = new List<string>());
            set => _indexeds = value;
        }

        public GetSpecPodMetadataConfigArgs()
        {
        }
        public static new GetSpecPodMetadataConfigArgs Empty => new GetSpecPodMetadataConfigArgs();
    }
}
