// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Inputs
{

    public sealed class GetSpecInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration needed to deploy a pod-based index.
        /// </summary>
        [Input("pod", required: true)]
        public Input<Inputs.GetSpecPodInputArgs> Pod { get; set; } = null!;

        /// <summary>
        /// Configuration needed to deploy a serverless index.
        /// </summary>
        [Input("serverless", required: true)]
        public Input<Inputs.GetSpecServerlessInputArgs> Serverless { get; set; } = null!;

        public GetSpecInputArgs()
        {
        }
        public static new GetSpecInputArgs Empty => new GetSpecInputArgs();
    }
}
