// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Inputs
{

    public sealed class GetSpecServerlessArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Ready.
        /// </summary>
        [Input("cloud", required: true)]
        public string Cloud { get; set; } = null!;

        /// <summary>
        /// Initializing InitializationFailed ScalingUp ScalingDown ScalingUpPodSize ScalingDownPodSize Upgrading Terminating Ready
        /// </summary>
        [Input("region", required: true)]
        public string Region { get; set; } = null!;

        public GetSpecServerlessArgs()
        {
        }
        public static new GetSpecServerlessArgs Empty => new GetSpecServerlessArgs();
    }
}
