// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Inputs
{

    public sealed class GetStatusInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Ready.
        /// </summary>
        [Input("ready", required: true)]
        public Input<bool> Ready { get; set; } = null!;

        /// <summary>
        /// Initializing InitializationFailed ScalingUp ScalingDown ScalingUpPodSize ScalingDownPodSize Upgrading Terminating Ready
        /// </summary>
        [Input("state", required: true)]
        public Input<string> State { get; set; } = null!;

        public GetStatusInputArgs()
        {
        }
        public static new GetStatusInputArgs Empty => new GetStatusInputArgs();
    }
}
