// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Inputs
{

    public sealed class GetStatusArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Ready.
        /// </summary>
        [Input("ready", required: true)]
        public bool Ready { get; set; }

        /// <summary>
        /// Initializing InitializationFailed ScalingUp ScalingDown ScalingUpPodSize ScalingDownPodSize Upgrading Terminating Ready
        /// </summary>
        [Input("state", required: true)]
        public string State { get; set; } = null!;

        public GetStatusArgs()
        {
        }
        public static new GetStatusArgs Empty => new GetStatusArgs();
    }
}
