// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Inputs
{

    public sealed class GetSpecPodMetadataConfigInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("indexeds", required: true)]
        private InputList<string>? _indexeds;

        /// <summary>
        /// The indexed fields.
        /// </summary>
        public InputList<string> Indexeds
        {
            get => _indexeds ?? (_indexeds = new InputList<string>());
            set => _indexeds = value;
        }

        public GetSpecPodMetadataConfigInputArgs()
        {
        }
        public static new GetSpecPodMetadataConfigInputArgs Empty => new GetSpecPodMetadataConfigInputArgs();
    }
}
