// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Inputs
{

    public sealed class IndexSpecGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration needed to deploy a pod-based index.
        /// </summary>
        [Input("pod")]
        public Input<Inputs.IndexSpecPodGetArgs>? Pod { get; set; }

        /// <summary>
        /// Configuration needed to deploy a serverless index.
        /// </summary>
        [Input("serverless")]
        public Input<Inputs.IndexSpecServerlessGetArgs>? Serverless { get; set; }

        public IndexSpecGetArgs()
        {
        }
        public static new IndexSpecGetArgs Empty => new IndexSpecGetArgs();
    }
}
