// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Inputs
{

    public sealed class IndexStatusGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Ready.
        /// </summary>
        [Input("ready")]
        public Input<bool>? Ready { get; set; }

        /// <summary>
        /// Initializing InitializationFailed ScalingUp ScalingDown ScalingUpPodSize ScalingDownPodSize Upgrading Terminating Ready
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        public IndexStatusGetArgs()
        {
        }
        public static new IndexStatusGetArgs Empty => new IndexStatusGetArgs();
    }
}
