// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PineconeDatabase.Pinecone.Inputs
{

    public sealed class PineconeSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration needed to deploy a pod index.
        /// </summary>
        [Input("pod")]
        public Input<Inputs.PineconePodSpecArgs>? Pod { get; set; }

        /// <summary>
        /// Configuration needed to deploy a serverless index.
        /// </summary>
        [Input("serverless")]
        public Input<Inputs.PineconeServerlessSpecArgs>? Serverless { get; set; }

        public PineconeSpecArgs()
        {
        }
        public static new PineconeSpecArgs Empty => new PineconeSpecArgs();
    }
}
