// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The `pinecone.Collection` resource lets you create and manage collections in Pinecone. Learn more about collections in the docs.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pinecone from "@pulumi/pinecone";
 *
 * const test = new pinecone.Index("test", {
 *     name: "tftestindex",
 *     dimension: 10,
 *     spec: {
 *         pod: {
 *             environment: "us-west4-gcp",
 *             podType: "s1.x1",
 *         },
 *     },
 * });
 * const testCollection = new pinecone.Collection("test", {
 *     name: "tftestcollection",
 *     source: test.name,
 * });
 * ```
 */
export class Collection extends pulumi.CustomResource {
    /**
     * Get an existing Collection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CollectionState, opts?: pulumi.CustomResourceOptions): Collection {
        return new Collection(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pinecone:index/collection:Collection';

    /**
     * Returns true if the given object is an instance of Collection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Collection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Collection.__pulumiType;
    }

    /**
     * The dimension of the vectors stored in each record held in the collection.
     */
    declare public readonly dimension: pulumi.Output<number>;
    /**
     * The environment where the collection is hosted.
     */
    declare public /*out*/ readonly environment: pulumi.Output<string>;
    /**
     * The name of the collection.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The size of the collection in bytes.
     */
    declare public readonly size: pulumi.Output<number>;
    /**
     * The name of the source index to be used as the source for the collection.
     */
    declare public readonly source: pulumi.Output<string>;
    /**
     * The status of the collection.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.CollectionTimeouts | undefined>;
    /**
     * The number of records stored in the collection.
     */
    declare public readonly vectorCount: pulumi.Output<number>;

    /**
     * Create a Collection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CollectionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CollectionArgs | CollectionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CollectionState | undefined;
            resourceInputs["dimension"] = state?.dimension;
            resourceInputs["environment"] = state?.environment;
            resourceInputs["name"] = state?.name;
            resourceInputs["size"] = state?.size;
            resourceInputs["source"] = state?.source;
            resourceInputs["status"] = state?.status;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["vectorCount"] = state?.vectorCount;
        } else {
            const args = argsOrState as CollectionArgs | undefined;
            if (args?.source === undefined && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            resourceInputs["dimension"] = args?.dimension;
            resourceInputs["name"] = args?.name;
            resourceInputs["size"] = args?.size;
            resourceInputs["source"] = args?.source;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["vectorCount"] = args?.vectorCount;
            resourceInputs["environment"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Collection.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Collection resources.
 */
export interface CollectionState {
    /**
     * The dimension of the vectors stored in each record held in the collection.
     */
    dimension?: pulumi.Input<number>;
    /**
     * The environment where the collection is hosted.
     */
    environment?: pulumi.Input<string>;
    /**
     * The name of the collection.
     */
    name?: pulumi.Input<string>;
    /**
     * The size of the collection in bytes.
     */
    size?: pulumi.Input<number>;
    /**
     * The name of the source index to be used as the source for the collection.
     */
    source?: pulumi.Input<string>;
    /**
     * The status of the collection.
     */
    status?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.CollectionTimeouts>;
    /**
     * The number of records stored in the collection.
     */
    vectorCount?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Collection resource.
 */
export interface CollectionArgs {
    /**
     * The dimension of the vectors stored in each record held in the collection.
     */
    dimension?: pulumi.Input<number>;
    /**
     * The name of the collection.
     */
    name?: pulumi.Input<string>;
    /**
     * The size of the collection in bytes.
     */
    size?: pulumi.Input<number>;
    /**
     * The name of the source index to be used as the source for the collection.
     */
    source: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.CollectionTimeouts>;
    /**
     * The number of records stored in the collection.
     */
    vectorCount?: pulumi.Input<number>;
}
