// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Index data source
 */
export function get(args: GetArgs, opts?: pulumi.InvokeOptions): Promise<GetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pinecone:index/get:get", {
        "embed": args.embed,
        "name": args.name,
        "spec": args.spec,
        "status": args.status,
    }, opts);
}

/**
 * A collection of arguments for invoking get.
 */
export interface GetArgs {
    /**
     * Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
     */
    embed?: inputs.GetEmbed;
    /**
     * Index name
     */
    name: string;
    spec?: inputs.GetSpec;
    status?: inputs.GetStatus;
}

/**
 * A collection of values returned by get.
 */
export interface GetResult {
    readonly deletionProtection: string;
    readonly dimension: number;
    /**
     * Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
     */
    readonly embed: outputs.GetEmbed;
    readonly host: string;
    readonly id: string;
    readonly metric: string;
    /**
     * Index name
     */
    readonly name: string;
    readonly spec: outputs.GetSpec;
    readonly status: outputs.GetStatus;
    readonly tags: {[key: string]: string};
    readonly vectorType: string;
}
/**
 * Index data source
 */
export function getOutput(args: GetOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pinecone:index/get:get", {
        "embed": args.embed,
        "name": args.name,
        "spec": args.spec,
        "status": args.status,
    }, opts);
}

/**
 * A collection of arguments for invoking get.
 */
export interface GetOutputArgs {
    /**
     * Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
     */
    embed?: pulumi.Input<inputs.GetEmbedArgs>;
    /**
     * Index name
     */
    name: pulumi.Input<string>;
    spec?: pulumi.Input<inputs.GetSpecArgs>;
    status?: pulumi.Input<inputs.GetStatusArgs>;
}
