// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Collection data source
 */
export function getCollection(args: GetCollectionArgs, opts?: pulumi.InvokeOptions): Promise<GetCollectionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pinecone:index/getCollection:getCollection", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getCollection.
 */
export interface GetCollectionArgs {
    /**
     * The name of the collection.
     */
    name: string;
}

/**
 * A collection of values returned by getCollection.
 */
export interface GetCollectionResult {
    /**
     * The dimension of the vectors stored in each record held in the collection.
     */
    readonly dimension: number;
    /**
     * The environment where the collection is hosted.
     */
    readonly environment: string;
    /**
     * Collection identifier
     */
    readonly id: string;
    /**
     * The name of the collection.
     */
    readonly name: string;
    /**
     * The size of the collection in bytes.
     */
    readonly size: number;
    /**
     * The status of the collection.
     */
    readonly status: string;
    /**
     * The number of records stored in the collection.
     */
    readonly vectorCount: number;
}
/**
 * Collection data source
 */
export function getCollectionOutput(args: GetCollectionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCollectionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pinecone:index/getCollection:getCollection", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getCollection.
 */
export interface GetCollectionOutputArgs {
    /**
     * The name of the collection.
     */
    name: pulumi.Input<string>;
}
