// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Indexes data source
 */
export function getEs(opts?: pulumi.InvokeOptions): Promise<GetEsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pinecone:index/getEs:getEs", {
    }, opts);
}

/**
 * A collection of values returned by getEs.
 */
export interface GetEsResult {
    /**
     * Indexes identifier
     */
    readonly id: string;
    /**
     * List of the indexes in your project
     */
    readonly indexes: outputs.GetEsIndex[];
}
/**
 * Indexes data source
 */
export function getEsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pinecone:index/getEs:getEs", {
    }, opts);
}
