// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { PineconeIndexResourceArgs } from "./pineconeIndexResource";
export type PineconeIndexResource = import("./pineconeIndexResource").PineconeIndexResource;
export const PineconeIndexResource: typeof import("./pineconeIndexResource").PineconeIndexResource = null as any;
utilities.lazyLoad(exports, ["PineconeIndexResource"], () => require("./pineconeIndexResource"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pinecone:index:PineconeIndexResource":
                return new PineconeIndexResource(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pinecone", "index", _module)
pulumi.runtime.registerResourcePackage("pinecone", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:pinecone") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
