// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApiKeyArgs, ApiKeyState } from "./apiKey";
export type ApiKey = import("./apiKey").ApiKey;
export const ApiKey: typeof import("./apiKey").ApiKey = null as any;
utilities.lazyLoad(exports, ["ApiKey"], () => require("./apiKey"));

export { CollectionArgs, CollectionState } from "./collection";
export type Collection = import("./collection").Collection;
export const Collection: typeof import("./collection").Collection = null as any;
utilities.lazyLoad(exports, ["Collection"], () => require("./collection"));

export { GetArgs, GetResult, GetOutputArgs } from "./get";
export const get: typeof import("./get").get = null as any;
export const getOutput: typeof import("./get").getOutput = null as any;
utilities.lazyLoad(exports, ["get","getOutput"], () => require("./get"));

export { GetCollectionArgs, GetCollectionResult, GetCollectionOutputArgs } from "./getCollection";
export const getCollection: typeof import("./getCollection").getCollection = null as any;
export const getCollectionOutput: typeof import("./getCollection").getCollectionOutput = null as any;
utilities.lazyLoad(exports, ["getCollection","getCollectionOutput"], () => require("./getCollection"));

export { GetCollectionsResult } from "./getCollections";
export const getCollections: typeof import("./getCollections").getCollections = null as any;
export const getCollectionsOutput: typeof import("./getCollections").getCollectionsOutput = null as any;
utilities.lazyLoad(exports, ["getCollections","getCollectionsOutput"], () => require("./getCollections"));

export { GetEsResult } from "./getEs";
export const getEs: typeof import("./getEs").getEs = null as any;
export const getEsOutput: typeof import("./getEs").getEsOutput = null as any;
utilities.lazyLoad(exports, ["getEs","getEsOutput"], () => require("./getEs"));

export { IndexArgs, IndexState } from "./index_";
export type Index = import("./index_").Index;
export const Index: typeof import("./index_").Index = null as any;
utilities.lazyLoad(exports, ["Index"], () => require("./index_"));

export * from "./provider";
import { Provider } from "./provider";


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pinecone:index/apiKey:ApiKey":
                return new ApiKey(name, <any>undefined, { urn })
            case "pinecone:index/collection:Collection":
                return new Collection(name, <any>undefined, { urn })
            case "pinecone:index/index:Index":
                return new Index(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pinecone", "index/apiKey", _module)
pulumi.runtime.registerResourceModule("pinecone", "index/collection", _module)
pulumi.runtime.registerResourceModule("pinecone", "index/index", _module)
pulumi.runtime.registerResourcePackage("pinecone", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:pinecone") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
