// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The `pinecone.Index` resource lets you create and manage indexes in Pinecone. Learn more about indexes in the [docs](https://docs.pinecone.io/guides/indexes/understanding-indexes).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pinecone from "@pulumi/pinecone";
 *
 * const test = new pinecone.Index("test", {
 *     name: "tftestindex",
 *     dimension: 10,
 *     spec: {
 *         serverless: {
 *             cloud: "aws",
 *             region: "us-west-2",
 *         },
 *     },
 * });
 * ```
 */
export class Index extends pulumi.CustomResource {
    /**
     * Get an existing Index resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IndexState, opts?: pulumi.CustomResourceOptions): Index {
        return new Index(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pinecone:index/index:Index';

    /**
     * Returns true if the given object is an instance of Index.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Index {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Index.__pulumiType;
    }

    /**
     * Whether deletion protection for the index is enabled. You can use 'enabled', or 'disabled'.
     */
    declare public readonly deletionProtection: pulumi.Output<string>;
    /**
     * The dimensions of the vectors to be inserted in the index
     */
    declare public readonly dimension: pulumi.Output<number>;
    /**
     * Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
     */
    declare public readonly embed: pulumi.Output<outputs.IndexEmbed>;
    /**
     * The URL address where the index is hosted.
     */
    declare public /*out*/ readonly host: pulumi.Output<string>;
    /**
     * The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If the 'vector_type' is 'sparse', the metric must be 'dotproduct'. If the vectorType is dense, the metric defaults to 'cosine'.
     */
    declare public readonly metric: pulumi.Output<string>;
    /**
     * The name of the index to be created. The maximum length is 45 characters.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Spec
     */
    declare public readonly spec: pulumi.Output<outputs.IndexSpec | undefined>;
    /**
     * Status
     */
    declare public /*out*/ readonly status: pulumi.Output<outputs.IndexStatus>;
    /**
     * Custom user tags added to an index. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '', or '-'. Values must be alphanumeric, ';', '@', '', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string}>;
    declare public readonly timeouts: pulumi.Output<outputs.IndexTimeouts | undefined>;
    /**
     * The index vector type. You can use 'dense' or 'sparse'. If 'dense', the vector dimension must be specified. If 'sparse', the vector dimension should not be specified.
     */
    declare public readonly vectorType: pulumi.Output<string>;

    /**
     * Create a Index resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IndexArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IndexArgs | IndexState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IndexState | undefined;
            resourceInputs["deletionProtection"] = state?.deletionProtection;
            resourceInputs["dimension"] = state?.dimension;
            resourceInputs["embed"] = state?.embed;
            resourceInputs["host"] = state?.host;
            resourceInputs["metric"] = state?.metric;
            resourceInputs["name"] = state?.name;
            resourceInputs["spec"] = state?.spec;
            resourceInputs["status"] = state?.status;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["vectorType"] = state?.vectorType;
        } else {
            const args = argsOrState as IndexArgs | undefined;
            resourceInputs["deletionProtection"] = args?.deletionProtection;
            resourceInputs["dimension"] = args?.dimension;
            resourceInputs["embed"] = args?.embed;
            resourceInputs["metric"] = args?.metric;
            resourceInputs["name"] = args?.name;
            resourceInputs["spec"] = args?.spec;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["vectorType"] = args?.vectorType;
            resourceInputs["host"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Index.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Index resources.
 */
export interface IndexState {
    /**
     * Whether deletion protection for the index is enabled. You can use 'enabled', or 'disabled'.
     */
    deletionProtection?: pulumi.Input<string>;
    /**
     * The dimensions of the vectors to be inserted in the index
     */
    dimension?: pulumi.Input<number>;
    /**
     * Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
     */
    embed?: pulumi.Input<inputs.IndexEmbed>;
    /**
     * The URL address where the index is hosted.
     */
    host?: pulumi.Input<string>;
    /**
     * The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If the 'vector_type' is 'sparse', the metric must be 'dotproduct'. If the vectorType is dense, the metric defaults to 'cosine'.
     */
    metric?: pulumi.Input<string>;
    /**
     * The name of the index to be created. The maximum length is 45 characters.
     */
    name?: pulumi.Input<string>;
    /**
     * Spec
     */
    spec?: pulumi.Input<inputs.IndexSpec>;
    /**
     * Status
     */
    status?: pulumi.Input<inputs.IndexStatus>;
    /**
     * Custom user tags added to an index. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '', or '-'. Values must be alphanumeric, ';', '@', '', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    timeouts?: pulumi.Input<inputs.IndexTimeouts>;
    /**
     * The index vector type. You can use 'dense' or 'sparse'. If 'dense', the vector dimension must be specified. If 'sparse', the vector dimension should not be specified.
     */
    vectorType?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Index resource.
 */
export interface IndexArgs {
    /**
     * Whether deletion protection for the index is enabled. You can use 'enabled', or 'disabled'.
     */
    deletionProtection?: pulumi.Input<string>;
    /**
     * The dimensions of the vectors to be inserted in the index
     */
    dimension?: pulumi.Input<number>;
    /**
     * Specify the integrated inference embedding configuration for the index. Once set, the model cannot be changed. However, you can later update the embedding configuration—including field map, read parameters, and write parameters.
     */
    embed?: pulumi.Input<inputs.IndexEmbed>;
    /**
     * The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If the 'vector_type' is 'sparse', the metric must be 'dotproduct'. If the vectorType is dense, the metric defaults to 'cosine'.
     */
    metric?: pulumi.Input<string>;
    /**
     * The name of the index to be created. The maximum length is 45 characters.
     */
    name?: pulumi.Input<string>;
    /**
     * Spec
     */
    spec?: pulumi.Input<inputs.IndexSpec>;
    /**
     * Custom user tags added to an index. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '', or '-'. Values must be alphanumeric, ';', '@', '', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    timeouts?: pulumi.Input<inputs.IndexTimeouts>;
    /**
     * The index vector type. You can use 'dense' or 'sparse'. If 'dense', the vector dimension must be specified. If 'sparse', the vector dimension should not be specified.
     */
    vectorType?: pulumi.Input<string>;
}
